server {
    listen 80;
    listen [::]:80;
    
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = /favicon.ico {
        alias /usr/share/nginx/html/favicon.ico;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
