server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = / {
        return 302 $scheme://$http_host/convert/;
    }

    location = /favicon.ico {
        alias /usr/share/nginx/html/convert/favicon.ico;
    }

    location /convert/ {
        try_files $uri $uri/ /convert/index.html;
    }
}
